from z3 import *

#variables
pbuff = IntVector('pbuff', 19)
rdLen = Int('rdLen')
IpbuffI = Int('IpbuffI')
bComSuc = Int('bComSuc')
bComSuc_next = Int('bComSuc_next')
cntLenRdS = Int('cntLenRdS')
cntLenRdS_next = Int('cntLenRdS_next')
totalLenRdS = Int('totalLenRdS')
totalLenRdS_next = Int('totalLenRdS_next')
cntLenRdO = Int('cntLenRdO')
cntLenRdO_next = Int('cntLenRdO_next')
totalLenRdO = Int('totalLenRdO')
totalLenRdO_next = Int('totalLenRdO_next')
frm = Int('frm')
frm_next = Int('frm_next')
cntCheckO = Int('cntCheckO')
cntCheckO_next = Int('cntCheckO_next')
cntCheckS = Int('cntCheckS')
cntCheckS_next = Int('cntCheckS_next')
cntHeadO = Int('cntHeadO')
cntHeadO_next = Int('cntHeadO_next')
cntHeadS = Int('cntHeadS')
cntHeadS_next = Int('cntHeadS_next')
cntUpdataO = Int('cntUpdataO')
cntUpdataO_next = Int('cntUpdataO_next')
cntUpdataS = Int('cntUpdataS')
cntUpdataS_next = Int('cntUpdataS_next')
totalCheckO = Int('totalCheckO')
totalCheckO_next = Int('totalCheckO_next')
totalCheckS = Int('totalCheckS')
totalCheckS_next = Int('totalCheckS_next')
totalHeadO = Int('totalHeadO')
totalHeadO_next = Int('totalHeadO_next')
totalHeadS = Int('totalHeadS')
totalHeadS_next = Int('totalHeadS_next')
totalUpdataO = Int('totalUpdataO')
totalUpdataO_next = Int('totalUpdataO_next')
totalUpdataS = Int('totalUpdataS')
totalUpdataS_next = Int('totalUpdataS_next')
chksum = Int('chksum')
chksum = 0
for i in range(18):
    chksum = chksum+pbuff[i] 
#Contract
s = Solver()
Check4 = And(Implies(chksum==pbuff[18], And(cntCheckO_next==0, cntCheckS_next==0, bComSuc==1)), Implies(chksum!=pbuff[18], And(cntCheckO_next==cntCheckO+1, cntCheckS_next==cntCheckS+1, totalCheckO_next==totalCheckO+1, totalCheckS_next==totalCheckS+1)))
Check3 = And(Implies(And(pbuff[0]==235, pbuff[1]==144), And(cntHeadO_next==0, cntHeadS_next==0, Check4)), Implies(Or(pbuff[0]!=235, pbuff[1]!=144), And(cntHeadO_next==cntHeadO+1, cntHeadS_next==cntHeadS+1, totalHeadO_next==totalHeadO+1, totalHeadS_next==totalHeadS+1)))
Check2 = And(Implies(pbuff[17]!=frm, And(cntUpdataO_next==0, cntUpdataS_next==0, frm_next==pbuff[17], Check3)), Implies(pbuff[17]==frm, And(cntUpdataS_next==cntUpdataS+1, cntUpdataO_next==cntUpdataO+1, totalUpdataO_next==totalUpdataO+1, totalUpdataS_next==totalUpdataS+1)))
Check1 = And(Implies(rdLen==19, And(cntLenRdS_next==0, Check2)), Implies(rdLen!=19, And(cntLenRdS_next==cntLenRdS+1, totalLenRdS_next==totalLenRdS+1, cntLenRdO_next==cntLenRdO+1, totalLenRdO_next==totalLenRdO+1)))
Assumptions = Implies(rdLen==19, IpbuffI>=19)
Guarantees = And(bComSuc==0, Check1)
s.add(Implies(Assumptions, Guarantees))
s.add(Assumptions)
###